name: "Build feature branch"

on:
  push:
    workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    name: Build Feature Branch
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      id: setup-java
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 8

    - name: Set up maven cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Maven package
      run: mvn --no-transfer-progress -B clean test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/surefire-reports/TEST-*.xml'
